// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQuprgKD9eRHJ5LBpsiRGcvmuOxMDCeXM',
    appId: '1:792979278445:web:6b2c52fd53d48303d00d64',
    messagingSenderId: '792979278445',
    projectId: 'fikirverse-425a9',
    authDomain: 'fikirverse-425a9.firebaseapp.com',
    storageBucket: 'fikirverse-425a9.appspot.com',
    measurementId: 'G-0RJ5R30HCE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvyVNhHylgpF1hco494Q_qfy2XX3D9D0M',
    appId: '1:792979278445:android:cff01dea53a88dc7d00d64',
    messagingSenderId: '792979278445',
    projectId: 'fikirverse-425a9',
    storageBucket: 'fikirverse-425a9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGOozxE6urYUqdxIfsjh5X1k_P4QZDOsc',
    appId: '1:792979278445:ios:4e13d4181574adadd00d64',
    messagingSenderId: '792979278445',
    projectId: 'fikirverse-425a9',
    storageBucket: 'fikirverse-425a9.appspot.com',
    iosClientId: '792979278445-5stjofea62krhfu54sdokj6ep2k8tvfn.apps.googleusercontent.com',
    iosBundleId: 'com.fikirverse.fikirverse',
  );
}
